# Generated by Django 2.1.3 on 2018-11-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuzcobot', '0002_auto_20181116_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='close',
        ),
        migrations.AddField(
            model_name='price',
            name='high',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='low',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='open',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='volume',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
